persistence:
  enabled: true
  size: 15Gi                
  storageClass: "openebs-hostpath"          

#password
existingSecret: "minio-secret"

mode: distributed           
replicas: 2

# buckets:                     
#   - name: "loki-data"     
#     policy: "none"           
#     purge: false           

console:
  enabled: true
  service:
    type: ClusterIP      

resources:
  requests:
    memory: 2Gi
    cpu: 500m
  limits:
    memory: 4Gi
    cpu: 1

service:
  type: ClusterIP         
  ports:
    console: 9001           
    api: 9000               
