apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-app-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi  
  storageClassName: openebs-hostpath

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
      # annotations:                  
        # prometheus.io/scrape: "true"
        # prometheus.io/port: "8080"   
        # prometheus.io/path: "/actuator/prometheus" 
    spec:
      containers:
        - name: spring-app
          image: nazmul4532brainstation/spring-boot-demo:latest
          ports:
            - containerPort: 8080
          volumeMounts: 
            - mountPath: /data  
              name: spring-app-storage  
          env:
            - name: OTEL_SERVICE_NAME
              value: "spring-app"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetry-collector-collector.otel.svc.cluster.local:4317"
      volumes:  
        - name: spring-app-storage
          persistentVolumeClaim:
            claimName: spring-app-pvc 
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  labels:
    app: spring-app
  # annotations:                    
  #   # prometheus.io/discover: "true" 
  #   # prometheus.io/path: "/actuator/prometheus"
  #   # prometheus.io/port: "8080"   
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-app
