service:
  enabled: true
  type: ClusterIP

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

grafana.ini:
  storage:
    type: s3
    bucket: "test"   
    access_key: "minioaccesskey" 
    secret_key: "miniosecretkey" 
    endpoint: "http://minioaccesskey:miniosecretkey@otel-minio-hl.minio-tenant.svc.cluster.local:9000" 
    secure: false  
    v4: true 
    http_timeout: 10s   
    
  smtp:
    enabled: true
    host: "smtp.gmail.com:587"
    fromName: "Grafana" 
    skipVerify: true  
    tls: true 
    sendReminder: false  

smtp:
  existingSecret: grafana-smtp-secret
  userkey: user
  passwordKey: password

persistence:
  enabled: true
  size: 5Gi
  storageClassName: openebs-hostpath

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.prometheus.svc.cluster.local:80
        isDefault: true
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-gateway.mimir.svc.cluster.local:8080/prometheus
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend.tempo.svc.cluster.local:3100

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.local.xyz
  tls:
    - hosts:
        - grafana.local.xyz
      secretName: grafana-ingress-tls


