service:
  enabled: true
  type: ClusterIP

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password


persistence:
  enabled: true
  size: 5Gi
  storageClassName: openebs-hostpath

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        isDefault: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.fintech23.xyz
  tls:
    - hosts:
        - grafana.fintech23.xyz
      secretName: fintech23xyz-ingress-tls


