mode: daemonset

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  exporters:
    otlp:
      endpoint: http://tempo-distributor.tempo.svc.cluster.local:9095
      tls:
        insecure: true
    otlphttp/prometheusremotewrite:
      endpoint: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
      tls:
        insecure: true
    otlphttp/logs:
      endpoint: http://loki-loki-distributed-distributor.loki.svc.cluster.local:3100/otlp
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp]
      metrics:
        receivers: [otlp]
        exporters: [otlphttp/prometheusremotewrite]
      logs:
        receivers: [otlp]
        exporters: [otlphttp/logs]

replicaCount: 1

image:
  repository: "otel/opentelemetry-collector-k8s"

presets:
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  logsCollection:
    enabled: true

resources:
  requests:
    memory: 500Mi
    cpu: 500m
  limits:
    memory: 1Gi
    cpu: 1

service:
  enabled: true
  name: opentelemetry-collector
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: 4317
    - port: 4318
      targetPort: 4318