apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

      exporters:
        otlp:
          endpoint: http://tempo-distributor.tempo.svc.cluster.local:4318
          tls:
            insecure: true
        prometheusremotewrite:
          endpoint: http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write
          tls:
            insecure: true
        otlphttp/logs:
          endpoint: http://loki-loki-distributed-distributor.loki.svc.cluster.local:3100/otlp
          tls:
            insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          exporters: [otlphttp/logs]
