apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath-minio
  labels:
    app.kubernetes.io/managed-by: NCC
    app.kubernetes.io/app: minio
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/appnk/minio"
    openebs.io/cas-type: local
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
