{
 "title": "Spring Boot Observability",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(job)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{job=\"$app_name\"})"
    }
   ]
  },
  {
   "title": "% 2xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (http_server_request_duration_seconds_count{job=\"$app_name\", http_response_status_code=~\"2.*\"}) / sum by(job) (http_server_request_duration_seconds_count{job=\"$app_name\"})",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "% Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (http_server_request_duration_seconds_count{job=\"$app_name\", http_response_status_code!~\"2.*\"})/ sum by(job) (http_server_request_duration_seconds_count{job=\"$app_name\"})",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_sum{job=\"$app_name\"}) / sum by(http_route) (http_server_request_duration_seconds_count{job=\"$app_name\"})",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_count{job=\"$app_name\"})",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (http_server_request_duration_seconds_count{job=\"$app_name\", http_response_status_code!~\"2.*\"})",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_count{job=\"$app_name\", http_response_status_code=~\"2.*\"}) / sum by(http_route) (http_server_request_duration_seconds_count{job=\"$app_name\"})",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Percent of Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_count{job=\"$app_name\", http_response_status_code!~\"2.*\"}) / sum by(http_route) (http_server_request_duration_seconds_count{job=\"$app_name\"})",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=\"$app_name\"}[$__range])) by(http_route, le))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_request_duration_seconds_bucket{job=\"$app_name\"}[$__range])) by(http_route, le))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{job=\"$app_name\"}[$__range]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=\"$app_name\"}[$__range])) by(job, le))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_request_duration_seconds_bucket{job=\"$app_name\"}[$__range])) by(job, le))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_server_request_duration_seconds_count{job=\"$app_name\"}[$__range]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(service_name) (rate({service_name=~\"$app_name\"} |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of Spring Boot App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "{service_name=~\"$app_name\"} |= \"$log_keyword\""
    }
   ]
  }
 ]
}